# Generated by Django 5.2.5 on 2025-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('category', models.IntegerField(choices=[(1, 'Electronics'), (2, 'Books'), (3, 'Clothing'), (4, 'Home & Kitchen'), (5, 'Beauty & Personal Care'), (6, 'Sports & Outdoors'), (7, 'Toys & Games'), (8, 'Automotive'), (9, 'Health'), (10, 'Other')], verbose_name='product category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
