# Generated by Django 5.2.5 on 2025-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='book title')),
                ('author', models.CharField(max_length=100, verbose_name='book author')),
                ('published_date', models.DateField(verbose_name='published date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['published_date'],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
