# Generated by Django 5.2.7 on 2025-10-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_deleted',
            field=models.BooleanField(default=False, verbose_name='article deleted'),
        ),
    ]
