# Generated by Django 5.2.5 on 2025-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='username')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'User Submission',
                'verbose_name_plural': 'User Submission',
            },
        ),
    ]
